version: "3.7"
services: 
  nginx:
    image: nginx:latest
    ports: 
      - 80:80
    networks: 
      - my-network
    deploy:
      replicas: 2

  db:
    image: mysql
    networks: 
      - my-network
    environment: 
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - db-storage:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.50'
          memory: 250M

networks: 
  my-network:

volumes: 
  db-storage:
    driver: local
    driver_opts:
      o: "size=10G"
      device: tmpfs
      type: tmpfs