version: "3.7"
services:
  app:
    image: jetalone/sails:latest
    working_dir: /application
    volumes:
      - ./application:/application
    command: ["sails", "lift", "--silly", "--drop"]

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx-debug, "-g", "daemon off;"]

  db:
    image: postgres
    restart: always
    volumes:
      - db-storage:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sails
      POSTGRES_DB: sails
      POSTGRES_PASSWORD: sails

  redis:
    image: redis:latest
    volumes:
      - redis-storage:/data
    entrypoint: ["redis-server", "--appendonly", "yes"]
    restart: always

volumes:
  db-storage:
  redis-storage:
