version: "3.7"
services: 
  wordpress:
    image: wordpress:5.3.2-php7.2-apache
    ports: 
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=database
    networks: 
      - front
      - backend

  db:
    image: mysql:5.7
    networks: 
      - backend
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes: 
      - db-storage:/var/lib/mysql

networks: 
  front: {}
  backend: {}

volumes:
  db-storage: {}

