version: "3.7"
services:
  application:
    image: containous/whoami:v1.4.0
    restart: on-failure
    depends_on: 
      - db
    networks: 
      - backend
      - frontend

  proxy:
    image: nginx
    volumes:
      - ./config/:/etc/nginx/
    ports:
      - "80:80"
    command: [nginx-debug, "-g", "daemon off;"]
    depends_on: 
      - application
    networks: 
      - frontend

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks: 
      - backend
    volumes: 
      - mysql-storage:/var/lib/mysql

networks: 
  backend:
  frontend:

volumes:
  mysql-storage: